import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/shared/styles/index.scss";
import Head from "next/head";

const roboto = localFont({
  src: [
    // Regular (300)
    {
      path: "../shared/assets/fonts/Roboto-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/Roboto-Light.woff",
      weight: "300",
      style: "normal",
    },

    // Regular (400)
    {
      path: "../shared/assets/fonts/Roboto-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/Roboto-Regular.woff",
      weight: "400",
      style: "normal",
    },

    // Medium (500)
    {
      path: "../shared/assets/fonts/Roboto-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/Roboto-Medium.woff",
      weight: "500",
      style: "normal",
    },

    // Semi-Bold (600)
    {
      path: "../shared/assets/fonts/Roboto-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/Roboto-SemiBold.woff",
      weight: "600",
      style: "normal",
    },

    // Bold (700)
    {
      path: "../shared/assets/fonts/Roboto-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../shared/assets/fonts/Roboto-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <body className={roboto.className}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
